### ISSUE TITLE
Create separate package  (hySpc.ggplot2) for gplot2 related functions

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.ggplot2#1]
I'm on my way to properly create **hySpc.ggplot2** package. 

- [x] Create repo  `r-hyperspec/hySpc.ggplot2`.
- [x] Copy **ggplot2* related functions from `cbeleites/hyperSpec` to  `r-hyperspec/hySpc.ggplot2`.
- [x] Review and update the documentation.
- [x] Add unit tests:
    + Several simple tests were added.
- [x] Update vignette:
    + The vignette was minimally updated. A more comprehensive update could be performed after the package is created.
- [x] Fix issues to make `r-hyperspec/hySpc.ggplot2` to pass R-CMD-check.
- [x] Create **pkgdown** website:
    + (Find it here: https://r-hyperspec.github.io/hySpc.ggplot2/).
- [x] Update the main webpage (https://r-hyperspec.github.io/) with the link to this repo.
- [x] Copy the **newest** labels (tags) from repo `cbeleites/hyperSpec`:
    + (@eoduniyi, can you help with this. I did not succeed in this task. BTW, labels in `hySpc.skeleton` are a bit out of date).
- [ ] License the package correctly:
    + (@cbeleites , could MIT be used for this package? Or GPL in **hyperSpec** does not allow this?)
- [x] Assign the authors and contributors correctly (currently only @cbeleites is included).
- [x] Properly deprecate appropriate functions in `r-hyperspec/hySpc.ggplot2`:
    + _The work is in progress: I'm working on a separate branch._

Some tasks are completed but in some places, I need @r-hyperspec/r-hyperspec's help/consultation: 

a) about the license, 
b) author and contributor list, 
c) about copying the newest labels from `cbeleites/hyperSpec` repo.

**Comment by eoduniyi** [comment]
Yes! I have updated the labels for the `hySpc.ggplot2` package (btw this was done using http://www.dorukdestan.com/github-label-manager/)

@GegznaV Could you check if the labels on `r-hyperspec:hySpc.skeleton` are still out of date? 
I updated them a couple of days ago. That being said, the labels recently attached to `hySpc.ggplot2` were derived from `hySpc.chondro`, which were derived from `hySpc.skeleton`.

**Comment by GegznaV** [comment]
@eoduniyi, it seems that several labels that are in `cbeleites/hyperSpec`, are missing in https://github.com/r-hyperspec/hySpc.skeleton So it is not up-to-date.

About the tool (http://www.dorukdestan.com/github-label-manager/), I try it by following instructions from several sources, unfortunately, it does not work for me as expected.

**Comment by eoduniyi** [comment]
Okay, well I think I all of the labels in `hySpc.chondro` are the same as the ones in  `cbeleites/hyperSpec`. The only hiccup I had was realizing that I can't copy label descriptions, so I have to manually copy and paste those in from another source (i.e., `cbeleites/hyperSpec`).  

So, I'll go ahead and update all of the repo labels this morning...but I do believe I'm going to need write-access to`hySpc.ggplot2` for what I'm trying to do.

**Comment by GegznaV** [comment]
I granted write access for the whole `@r-hyperspec/r-hyperspec` team last week. Doesn't it work?

**Comment by eoduniyi** [comment]
> I granted write access for the whole `@r-hyperspec/r-hyperspec` team last week. Doesn't it work?

It does and labels updated sir.

**Comment by GegznaV** [comment]
The package is created, so I'm closing this. Yet, I'll open an issue related to licence.
